site_name: DGPrincess

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: purple
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
nav:
  - Home: index.md
  - Quickstart: about.md
  - Tutorial:
    - tutorial/hello-lemonade.md
    - tutorial/add-products.md
    - tutorial/add-customers.md
    - tutorial/add-db-analytics.md
    - Give customers preferences across products: tutorial/add-customer-prefs.md
    - Model data entry errors: tutorial/model-data-entry-errors.md
    - Model customer churn: tutorial/model-customer-churn.md
    - Run marketing campaigns: tutorial/run-marketing-campaigns.md
    - Acquire another lemonade stand: tutorial/acquire-lemonade-stand.md

  - Core concepts:
    - Overview: core-concepts/overview.md
    - Entity: core-concepts/entity.md
    - Event: core-concepts/event.md
    - Simulation: core-concepts/simulation.md
  - Recipes:
    - Changing entity types: examples/example2.md
    - Event formats that must be normalized: examples/example2.md
    - y
    - z
  - Contributing: contributing.md