site_name: DGPrincess

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: purple
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
nav:
  - Home: index.md
  - Quickstart: about.md
  - Tutorial:
    - tutorial/hello-lemonade.md
    - Add more products: tutorial/add-products.md
    - Add customers: tutorial/add-products.md
    - tutorial/add-db-analytics.md
    - Give customers preferences across products: tutorial/add-db-analytics.md
    - Data entry errors: examples/example2.md
  - Core concepts:
    - Overview: core-concepts/overview.md
    - Entity: core-concepts/entity.md
    - Event: core-concepts/event.md
    - Simulation: core-concepts/simulation.md
  - Recipes:
    - Changing entity types: examples/example2.md
    - Event formats that must be normalized: examples/example2.md
    - y
    - z
  - Contributing: contributing.md